name: "personal-website-catalina-medina"
title: "My Website"
output_dir: "docs"
repository_url: https://github.com/CatalinaMedina/CatalinaMedina.github.io
navbar:
  source_url: true
  right:
    - text: "Home"
      href: index.html
    - text: "CV"
      href: 
    - text: "Teaching"
      href: 
    - text: "Research"
      href: 
output: 
  distill::distill_article